name: Service Containers Practice

on:
  push:
  workflow_dispatch:

jobs:
  service-containers-demo:
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx:alpine
        ports:
          - 8080:80

      apache:
        image: httpd:2.4
        ports:
          - 8081:80

    steps:
      - name: Check NGINX Service
        run: |
          echo "Checking NGINX..."
          curl -f http://localhost:8080

      - name: Check Apache Service
        run: |
          echo "Checking Apache..."
          curl -f http://localhost:8081
